### ISSUE TITLE
Update illuminate packages

### ISSUE THREAD

**Issue by leroy0211** [wouterj/WouterJEloquentBundle#102]
You should update the illuminate packages to `^5.5` instead of `~5.5`. Illuminate won't introduce BC breaks in minors. So that's pretty safe to do.

**Comment by wouterj** [comment]
This is only the case for Laravel 6+ (See https://laravel.com/docs/5.8/releases ). But indeed, this bundle should be updated to support Laravel 5.8 (which probably means dropping some older Laravel 5.x versions).

Today, I restarted work on this bundle in #101. Let get that merged and then focus on adding support for newer Laravel versions. Feel free to help :)

**Comment by wouterj** [comment]
This is going to be fixed by https://github.com/wouterj/WouterJEloquentBundle/pull/106 . It was surprisingly easy to support 5.7 and 5.8 (compared to anything before 5.6)
