### ISSUE TITLE
Attempted to call an undefined method named "getCasts"

### ISSUE THREAD

**Issue by JordinMarshall** [wouterj/WouterJEloquentBundle#103]
This error is being thrown in a bundle with no association to anything regarding to the WouterJEloquentBundle

Fatal error: Uncaught Symfony\Component\Debug\Exception\UndefinedMethodException: Attempted to call an undefined method named "getCasts" of class "Content\PollBundle\Entity\PollVersion". in /var/www/html/vendor/wouterj/eloquent-bundle/src/Form/EloquentModelTypeGuesser.php on line 23
--
 Symfony\Component\Debug\Exception\UndefinedMethodException: Attempted to call an undefined method named "getCasts" of class "Content\PollBundle\Entity\PollVersion". in /var/www/html/vendor/wouterj/eloquent-bundle/src/Form/EloquentModelTypeGuesser.php on line 23

This is occurring in a couple of our bundles

**Comment by wouterj** [comment]
Thank you for reporting this issue!

It appears there was a bug in the form type guesser (I somehow assumed it was only called for eloquent models). This should be fixed by in 1.0.3. Please let me know if you still have this error after updating.
