### ISSUE TITLE
Somebody once told me the world is gonna roll me

### ISSUE THREAD

**Issue by x8core** [wouterj/WouterJEloquentBundle#112]
Many links of docs in README going to 404s.
Examples:
https://github.com/wouterj/WouterJEloquentBundle/blob/master/Resources/docs/usage.rst#query-builder
https://github.com/wouterj/WouterJEloquentBundle/blob/master/Resources/docs/usage.rst#eloquent-orm

**Comment by wouterj** [comment]
Feel free to submit a PR to fix it. And otherwise please remain silent if you can't communicate issues respectfully.

**Comment by x8core** [comment]
Maybe we need to close all issues on github and propose people to feel free to submit PRs?

**Comment by wouterj** [comment]
Yes, if it's small textual changes definitely. It's open source, meaning we all invest a bit (of lots of bits) of free time to help someone else fix problems. This "all" is very important, it's not just the maintainer that should invest free time in helping other solve problems. It's something that you do together, as users and maintainers. That is called *contributing*.

From time to time, users of open source expect things to only be done for them, which is exactly the opposite of this idea. If it's small typos like this one, I'm often fine with it. However, if that is combined with quoting unrespectful song texts or saying "you're a robot", it comes to a point were I just start to completely ignore the reported issue.

**Comment by x8core** [comment]
Actually, i don't want to hurt you, so sorry for my behaviour. About song quote, i thought it would be funny not unrespectful. I don't mean that you are robot.
