### ISSUE TITLE
eloquent:migrate throws Call to a member function getRequire() on null

### ISSUE THREAD

**Issue by TBaak** [wouterj/WouterJEloquentBundle#136]
When I run the `$ php bin/console eloquent:migrate` command it fails with a `Call to a member function getRequire() on null` error.

Steps to recreate:

1. `$ symfony new symfony-eloquent && cd symfony-eloquent`
2. `$ composer require wouterj/eloquent-bundle`
3. `$ composer require --dev symfony/maker-bundle`
4. `$ php bin/console make:model Post`
5. `$ php bin/console eloquent:migrate:install`
6. `$ php bin/console make:eloquent-migration --create=posts create_posts_table`
7. `$ php bin/console eloquent:migrate`

Packages:

1. `"symfony/framework-bundle": "6.3.*"`
2. `"wouterj/eloquent-bundle": "^2.4"`
3. `"symfony/maker-bundle": "^1.49"`

PHP:

1. `PHP 8.1.6`

Model:

```
namespace App\Model;

use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
}
```
Migration:

```
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use WouterJ\EloquentBundle\Facade\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('post', function (Blueprint $table) {
            $table->id();
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('post');
    }
};
```

**Comment by wouterj** [comment]
Hi! Thank you for the report. This should now be fixed with 2.4.1
