### ISSUE TITLE
Eloquent not booted

### ISSUE THREAD

**Issue by Whyounes** [wouterj/WouterJEloquentBundle#31]
I got an error while using the User model inside a `LoginFormAuthenticator` class (I'm implementing guard component). It says `Error: Call to a member function connection() on null`!

After looking around for a while I figured out Eloquent has not booted! And after adding a `$capsuleDefinition->addMethodCall('bootEloquent');` inside the `WouterJ\EloquentBundle\DependencyInjection\WouterJEloquentExtension@loadCapsule` it worked fine.

**Comment by wouterj** [comment]
@Whyounes can you please check again with dev-master? I'm about to release it as a new minor release and it should fix booting errors. It would be great to get feedback on it before I release it.

**Comment by Whyounes** [comment]
I will try to try it this weekend

**Comment by Whyounes** [comment]
The package isn't installable via Composer. I guess you have done something wrong in your package requirements versions!

**Comment by theofidry** [comment]
? @Whyounes not sure what you mean, I'm heavily relying on this in https://github.com/theofidry/AliceDataFixtures

**Comment by Whyounes** [comment]
I'm always getting this error.

![screen](https://www.dropbox.com/s/it8u9nfdflrg463/Screenshot%202016-11-08%2022.22.52.png?dl=0)

**Comment by theofidry** [comment]
@Whyounes links broken :/

**Comment by Whyounes** [comment]
Sorry, fixed

**Comment by theofidry** [comment]
The package is `wouterj/eloquent-bundle`, not `wouterj/wouterjeloquentbundle` :)

**Comment by Whyounes** [comment]
I tried it, but still getting the same error! Could this be a problem in my app??

**Comment by theofidry** [comment]
did you try with the right stability version? If your package.json is configured with `minimum-version` set to `stable` (default), you cannot install an unstable package (i.e. which has no stable version yet) without specifying the stability tag (`composer require routerj/eloquent-bundle:^1.0@dev` which points to `dev-master`) or using an unstable version (`composer require routerj/eloquent-bundle:^0.2`)

**Comment by Whyounes** [comment]
Still getting the same error, I don't know why this is happening!!

**Comment by theofidry** [comment]
Without your `composer.json` or knowing exactly what the error is it's a bit hard to tell. But in any case this should be discussed in a dedicated issue not this thread.

**Comment by arondraper** [comment]
Hello guys I'm having a similar issue.  

If I want to query the database without creating any models it works fine.  I create a 'Page' model and try to query the model for a page id.  var dump it to the browser but symfony reports the error: Error: Call to a member function connection() on null

I've tried using dev-master instead of ^0.2 but still does it.  It might be something simple im missing but its got me stuck at the min. 

Ive added some screenshots of my model, composer update, symfony error and an example of my call to the model.  Can you guys offer any guidance to what Im doing wrong or how I can make it work?  Many Thanks

https://www.dropbox.com/sh/ss8lxkmr0a5ls0h/AABBNSeoZE8EX8tRRMgRYA2Ba?dl=0

**Comment by arondraper** [comment]
I managed to get it working (but it's not the best way to do it) by adding a capsule connection in the constructor of the model.  Im pretty sure there's probably a better way (at least where its using the db settings from config.yml).

<img width="1153" alt="screen shot 2016-11-26 at 09 47 05" src="https://cloud.githubusercontent.com/assets/4047428/20639515/7820403c-b3bd-11e6-93b6-7e954c8b624f.png">

so now $page = Page::find(1);  does return the model when var dumped with the right data.

**Comment by Whyounes** [comment]
@arondraper You only need to boot Eloquent somewhere. The connection details and globals are working fine (at least for me).

**Comment by arondraper** [comment]
@Whyounes thank you  =)  

I tried to boot eloquent without adding the connection and it complains about 'Database [default] not configured'.  Do you know how I set the default db connection?
```
$capsule = new Capsule();
$capsule->bootEloquent();
$capsule->setAsGlobal();
```
<img width="805" alt="screen shot 2016-11-26 at 10 47 40" src="https://cloud.githubusercontent.com/assets/4047428/20639830/e67580b2-b3c5-11e6-8456-0a302ff11eba.png">

**Comment by Whyounes** [comment]
You should resolve the capsule instance from the container and boot eloquent. Not create a new instance!
