### ISSUE TITLE
Mention EloquentSerializer

### ISSUE THREAD

**Issue by theofidry** [wouterj/WouterJEloquentBundle#39]
https://github.com/theofidry/EloquentSerializer is a simple bridge for Symfony serializer to work with an Eloquent model

It is not really in the scope of this bundle, but as it's the main bundle to use Eloquent within Symfony, feels like it should be the one mentioning other related packages.

**Comment by wouterj** [comment]
Hi @theofidry! I think it's fine to mention Eloquent - Symfony related tools in the readme file. However, I would like to mention packages that are stable. I can understand that you probably wait for this bundle's stable, so after that, I'll happily accept adding a reference to that package (and maybe also your alice fixtures bundle).

**Comment by theofidry** [comment]
I'll do a PR once the stable releases are out then :) Should happen soon 😄
