### ISSUE TITLE
variation of postgres driver names

### ISSUE THREAD

**Issue by narutimateum** [wouterj/WouterJEloquentBundle#43]
illuminate searches for pgsql
whilst wouterj searches for postgres
and doctrine registers postgres driver as pdo_pgsql

can you add the validation of config for drivers ->ifNotInArray(['mysql', 'pgsql', 'sql server', 'sqlite'])
to more possible combinations ?
-postgres
-pgsql
-pdo_pgsql
-postgresql

??

if i use all these names above it wont work unless i change the validation from postgres to pgsql and use pgsql

**Comment by theofidry** [comment]
Maybe you could try to open a PR for it? I believe it's just a matter of editing the configuration.

I would keep the driver name to what Eloquent uses rather than doctrine.

**Comment by narutimateum** [comment]
i have checked what eloquent uses.. its "pgsql"  but wouterj use postgres

**Comment by narutimateum** [comment]
how do i do a pull request?

**Comment by theofidry** [comment]
Sorry I was off before seeing your message, but I guess you figured it out with #44 😄
