### ISSUE TITLE
Integrate model events

### ISSUE THREAD

**Issue by wouterj** [wouterj/WouterJEloquentBundle#6]
http://laravel.com/docs/5.0/eloquent#model-events

**Comment by mtotheikle** [comment]
Would you mind elaborating on what you see this looking like? We use this bundle for all of our projects at work and just use Laravel dispatcher by calling something similar to: `$this->container->get('wouterj_eloquent')->setEventDispatcher(new \Illuminate\Events\Dispatcher());`

**Comment by WouterJ** [comment]
I guess we can implement it in 2 different ways:

 * Use the Illuminate events component (like you did) and make everyone use illuminate's event listeners for their Eloquent listeners.
 * Create some sort of bridge between Illuminate's event dispatcher and the one in Symfony, allowing people to use the Symfony-style listener for their model event listeners.

I tend to think that the second option should be the way forward. After all, this bundle is implementing Eloquent in Symfony, not the Laravel API.
