### ISSUE TITLE
db port can not be set through config

### ISSUE THREAD

**Issue by uddhab** [wouterj/WouterJEloquentBundle#69]

**Comment by duayres** [comment]
I can confirm that the configuration doesnt process a port yet, I'm doing a PR to fix that.

**Comment by duayres** [comment]
Done a PR. If you want to put it to work right away only get my modified /wouterj/eloquent-bundle/ser/DependecyInjection/Configuration.php file ... oh, on this PR #70

**Comment by wouterj** [comment]
#70 is now merged and will now be available in `1.0.0@dev`. I'm almost going to release 1.0 stable.
