### ISSUE TITLE
Add generate command

### ISSUE THREAD

**Issue by wouterj** [wouterj/WouterJEloquentBundle#7]
`php app/console eloquent:make:model User`

**Comment by duayres** [comment]
You plan to generate the model with the attributes on it?

**Comment by wouterj** [comment]
@duayres I have not yet planned anything for this feature, so I'm open for any suggestion :).

In case you (or anyone else) wants to work on this, I would welcome a very simple make command that just generates the file + basic class definition (like the [basic migration stub](https://github.com/illuminate/database/blob/master/Migrations/stubs/blank.stub)). One step further would be to similate the [`make:entity` command](https://github.com/symfony/maker-bundle/blob/master/src/Maker/MakeEntity.php) from Symfony's MakerBundle.

However, as this bundle still supports 2.8, we cannot use the Symfony MakerBundle :(

**Comment by theofidry** [comment]
@wouterj is there any point to keep 2.8 support? Just bump to 3.4+ :)

**Comment by duayres** [comment]
I recommend at least 3.3

**Comment by wouterj** [comment]
This bundle is not very popular (yet) and I know one of the companies using it is still on Symfony 2.8. So I keep support for it till eom.
