### ISSUE TITLE
Tag a new version to have symfony 4 support in a tagged release

### ISSUE THREAD

**Issue by robertfausk** [wouterj/WouterJEloquentBundle#73]

**Comment by wouterj** [comment]
I'll wait for Symfony 4 stable until tagging 1.0 of this bundle (with Symfony 4 support). Without a stable release, I'm not sure if this bundle is stable. And releasing a 1.0 version of a bundle without some feeling of stability seems weird to me.

Anyway, this one will have 1.0 stable within a week of Symfony 4 stable (so before December the 8th). I'll promise!

**Comment by robertfausk** [comment]
What about tagging a RC or beta tag?
Then WouterJEloquentBundle can be used by other libraries by now.

Otherwise I'm also fine with a tag before december the 8th.

**Comment by theofidry** [comment]
We can wait a few weeks it's ok :)

**Comment by wouterj** [comment]
Here you go: https://github.com/wouterj/WouterJEloquentBundle/releases/tag/1.0.0-RC1

**Comment by robertfausk** [comment]
Whoop whoop!
