### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by raffaelecarelle** [wouterj/WouterJEloquentBundle#77]
I have symfony 4.0 version installed.

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install symfony/dependency-injection v3.4.0
    - Installation request for symfony/dependency-injection (locked at v4.0.0) -> satisfiable by symfony/dependency-injection[v4.0.0].
    - Conclusion: remove symfony/console v4.0.0
    - Conclusion: don't install symfony/console v4.0.0
any suggest?

Thank you

**Comment by wouterj** [comment]
Hi!

Only 1.0.0-RC supports Symfony 4.0 at the moment (I'm about to test it in a Symfony 4 app before releasing it as stable). So for now, you have to do something like `composer req wouterj/eloquent-bundle:@rc` to install & test the RC release with symfony 4.

For now, I'm going to close this issue. I'll let you know when I release stable!

**Comment by wouterj** [comment]
For your information, 1.0 is now released. Besides this, a new flex recipe is also published, so installation should be as easy as `composer req wouterj/eloquent-bundle`

**Comment by raffaelecarelle** [comment]
Thank you very much !
