### ISSUE TITLE
Adding a Login with Eloquent?

### ISSUE THREAD

**Issue by iplayguitar81** [wouterj/WouterJEloquentBundle#82]
Is this possible? If so, are there instructions or a tutorial on how to do so using the WouterJEloquentBundle?

**Comment by theofidry** [comment]
Eloquent is just here to interact with your database, any login-security feature is out of the scope of this library.

To build a login form relying on [this documentation](https://symfony.com/doc/current/security/form_login_setup.html) or via a third-party bundle like FosUserBundle

**Comment by duayres** [comment]
Yes it is possible, but you will need to create a custom user provider as refered [here](https://symfony.com/doc/current/security/custom_provider.html).
Your model class should extend from eloquent model, then must implements UserInterface and EquatableInterface interfaces, and for everything else use Security Guard or something out-of-the-box like what @theofidry mentioned.

**Comment by iplayguitar81** [comment]
Thanks for the responses guys.  @duayres I tried to create a custom user provider and am running into challenges using Symfony 4.
