### ISSUE TITLE
Error with pagination

### ISSUE THREAD

**Issue by tsdevelopment** [wouterj/WouterJEloquentBundle#83]
Whenever I Use the pagination I get the following error:

`Attempted to load class "Paginator" from namespace "Illuminate\Pagination".
Did you forget a "use" statement for "Illuminate\Contracts\Pagination\Paginator"?`

Can you enable more Aliases to use the paginator class?

**Comment by theofidry** [comment]
AFAICT it's a package on its own: https://github.com/illuminate/pagination so you need to install it to be able to use it.
