### ISSUE TITLE
Seeder class names losses their first letter

### ISSUE THREAD

**Issue by mariano-gomez** [wouterj/WouterJEloquentBundle#86]
Hi guys, i've found that executing:
 ./bin/console eloquent:make:seeder --target=migrations/seeds/SomeClass.php SomeClass, a file is created in migrations/seeds/ with the correct filename. But inside the file, a class is defined with the name "omeClass"

The problem is in class wouterj\eloquent-bundle\src\Command\SeederMakeCommand.php, on line 65 ($class = substr($name, $lastPos + 1);)

that +1 shouldn't exists

**Comment by wouterj** [comment]
Ah, thanks for finding this bug and proposing a fix. Can you maybe create a PR yourself, so I can give you full credits? (you can do so by navigating to this file in github and clicking "edit" in the top right)

**Comment by wouterj** [comment]
Fixed by #90
