### ISSUE TITLE
Postgresql Schemas

### ISSUE THREAD

**Issue by valentimlh** [wouterj/WouterJEloquentBundle#91]
There is no param on eloquent.yaml to set schema for postgresql database.

I was able to make it work by editing the file:  **WouterJEloquentBundle/src/DependencyInjection/Configuration.php** and inserting the param 'schema'  to the arrays on lines 82, 86 and adding: **->scalarNode('schema')->defaultValue('')->end()** below line 139.

Can you add this to the master please ?

**Comment by duayres** [comment]
You can contribute to this project, just follow this example [here](https://github.com/wouterj/WouterJEloquentBundle/pull/70/commits/d9a8b3b6f800b43090d5d17ecf92d874676d2e51) and make your PR.  Are you able to do this?
